### ISSUE TITLE
Setup Helm charts

### ISSUE THREAD

**Issue by zioCristia** [eupneart/cloud#3]
It could be useful to generate a helm repository in GitHub, this can be done with a GitHub Action created by Helm itself. More info here: https://helm.sh/docs/howto/chart_releaser_action/

```
# Example Chart.yaml
apiVersion: v2
name: pfx-namespace
description: Chart to create the namespace in a platform
type: application
version: 0.0.1
dependencies:
- name: ns
  repository: "https://repository.test.net:443/artifactory/cca-helm-prod-cca/"
  version: "1.0.4"
```

values.yaml to be added.

```
# Example ApplicationSet to be used from argocd
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: static-pfx-dev
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: tst-ne-cur01a
            subscription: amacp-tst-ne-cur-01
          - cluster: tst-ne-cur01b
            subscription: amacp-tst-ne-cur-01
          - cluster: tst-ne-shop06a
            subscription: amacp-tst-ne-shopping-02
          - cluster: tst-ne-shop06b
            subscription: amacp-tst-ne-shopping-02
      - list:
          elements:
          - phase: dev
  template:
    metadata:
      name: 'pfx-static-{{ cluster }}-{{ phase }}'
      annotations:
       argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: 'pfx-{{ phase }}'
      source:
        repoURL: https://bitbucket.gob.amadeus.net/scm/PIONEERAPEPFX/deployment.git
        targetRevision: feature/nas_setup
        path: 'static/pfx/{{ phase }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - ../values-common.yaml
          - ../values-{{ subscription }}.yaml
          - ../values-{{ cluster }}.yaml
          - values-{{ phase }}.yaml
          - values-{{ cluster }}-{{ phase }}.yaml
      destination:
        name: '{{ cluster }}'
        namespace: 'pfx-{{ phase }}'
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
```

Add CI checks
```
helm lint ./mychart
helm template --debug mychart
```

https://github.com/DevOps-Nirvana/Universal-Kubernetes-Helm-Charts/blob/master/templates/_helpers.tpl
https://github.com/stakater/application/blob/master/application/values-test.yaml
