### ISSUE TITLE
Add monitoring tools (Prometheus and Graphana)

### ISSUE THREAD

**Issue by zioCristia** [eupneart/cloud#5]
To check if we want Graphana or Dynatrace instead.

Interesting graph to put in Graphana:
- Traffic (per pod and overall per cluster)
- Dequeue rate if already added
- Liveness of deployments

https://spacelift.io/blog/prometheus-kubernetes
https://medium.com/@divyam.sharma3/centralized-logging-for-microservices-on-eks-cluster-with-the-efk-stack-3d87f9d32f1f

Check also if the readiness and liveness is used, if not add it in the charts:
```
livenessProbe:
  httpGet:
    path: /actuator/health/liveness  
    port: http
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: htt
```

(optional) Install Prometheus ServiceMonitors to collect controller and cloudflared metrics: `kubectl apply -k "github.com/pl4nty/cloudflare-kubernetes-gateway//config/prometheus?ref=v0.8.1"`

Track:

CPU
- [ ] memory
- [ ] rest latency
- [ ] HTTP errors
- [ ] pod restarts
- [ ] DB usage
- [ ] MinIO storage
- [ ] node disk usage
- [ ] disk space.
